/*
 * SettingsForm.java
 * 
 * Version 1.0
 *
 * Created on Nov 30, 2011, 9:11:12 AM
 * 17 May 2013
 */
package com.bixly.pastevid.screencap.components.settings;

import com.bixly.pastevid.recorders.Recorder;
import com.bixly.pastevid.screencap.RecorderPanel;
import com.bixly.pastevid.util.LogUtil;
import com.bixly.pastevid.util.view.MouseMoveListener;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author cevaris
 */
public class SettingsForm extends javax.swing.JFrame {
    
    private SettingsPanel jpSettings;
    private RecorderPanel jpRecorder;
    private Recorder      recorder;
    
    /** 
     * Creates new form SettingsForm 
     */
    public SettingsForm() {
        initSettingsPanel();
        this.setName("settingsForm");
    }
    
    public void setRecorderPanel(RecorderPanel panel) {
        this.jpRecorder = panel;
        if (this.jpSettings != null) {
            this.loadSmartPosition();
        }
    }

    /**
     * Enables or disables input for the video quality slider.
     * Only used in JUnit tests.
     * @param bln True to enable
     */
    public void setEnableControl(boolean bln) {
        this.jpSettings.setEnableControls(bln);
    }

    public void setRecorder(Recorder recorder) {
        this.recorder = recorder;
        if (this.jpSettings != null) {
            jpSettings.setRecorder(recorder);
        }
    }

    public SettingsPanel getPanel() {
        return this.jpSettings;
    }
    
    /**
     * Re-positions the settings panel relative to the recorder.
     */
    public void loadSmartPosition() {
        // Bounds of the current screen
        Dimension bounds = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocationRelativeTo(this.jpRecorder.getRootPane());
        Point offset = this.getLocation();
        
        if ((offset.y + 150) > bounds.getHeight()) {
            offset.y -= 50;
        } else {
            offset.y += 50;
        }
        
        // Set new cooridnates
        this.setLocation(offset);
    }
    
    /**
     * Initializes the settings panel.
     */
    private void initSettingsPanel() {
        int startX = 30;
        int startY = 30;
        
        try {
            this.setLocation(startX, startY);
            this.dispose();
        } catch (Exception e) {
        }
        
        jpSettings = new SettingsPanel();
        MouseMoveListener mml = new MouseMoveListener(jpSettings);
        this.addMouseListener(mml);
        this.addMouseMotionListener(mml);
        
        this.setAlwaysOnTop(true);
        this.setUndecorated(true);
        
        try {
            if (!AWTUtilities.isTranslucencyCapable(this.getGraphicsConfiguration())) {
                log("Can not set transparency for settings form");
                this.setBackground(new Color(64, 64, 64, 255));
                this.jpSettings.setBackground(new Color(64, 64, 64, 255));
                this.jpSettings.setOpaque(true);
            } else {
                log("Transparency is set for settings form");
                AWTUtilities.setWindowOpaque(this, false);
            }
        } catch (Exception ex) {log(ex);}
        
        this.add(jpSettings);
        
        // Hack for handling draggable JFrames on Mac OSX
        this.getRootPane().putClientProperty("apple.awt.draggableWindowBackground", Boolean.FALSE);
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocation(startX, startY);
        this.pack();
        this.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(64, 64, 64));
        setName("settingsForm"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void showSettingsForm() {
        this.jpSettings.loadPastevidSettings();
        this.setVisible(true);
    }
    public void hideSettingsForm() {
        this.setVisible(false);
    }

    public void log(Object message) {
        LogUtil.log(SettingsForm.class, message);
    }
}
