/*
 * HBorder.java
 *
 * Version 1.0
 * 
 * 16 May 2013
 */
package com.bixly.pastevid.screencap.components.capturebox;

import java.awt.Color;
import java.awt.GraphicsDevice;
import javax.swing.JWindow;

/**
 * Horizontal border for the top and bottom sides of a CaptureBox.
 * @author June Millan
 */
public final class HBorder extends JWindow {
    // Location flags
    public static final int AT_TOP = 0;
    public static final int AT_BOTTOM = 1;
    private int boxLocation = AT_TOP;
    
    // Border colors
    public static final Color BORDER_COLOR = new Color(68, 149, 173, 255);
    public static final Color BORDER_FLASH_COLOR = new Color(219, 53, 53);

    
    /**
     * Creates a new form HBorder.
     * @param location 
     */
    public HBorder(int location) {
        this.setBoxLocation(location);
        this.setFocusableWindowState(false);
        this.getContentPane().setBackground(BORDER_COLOR);
        this.setAlwaysOnTop(true);
        initComponents();
    }

    /**
     * Creates a new form HBorder on the given GraphicsDevice.
     * @param location
     * @param device 
     */
    public HBorder(int location, GraphicsDevice device) {
        super(device.getDefaultConfiguration());
        this.setFocusableWindowState(false);
        this.setBoxLocation(location);
        this.getContentPane().setBackground(BORDER_COLOR);
        this.setAlwaysOnTop(true);
        initComponents();
    }

    /**
     * Sets HBorder location.
     * @param location 0 == AT_TOP; 1 == AT_BOTTOM;
     */
    public void setBoxLocation(int location) {
        this.boxLocation = (location > AT_TOP || location < AT_BOTTOM) ? AT_TOP : location;
    }

    /**
     * Returns HBorder location (AT_TOP|AT_BOTTOM)
     * @return 
     */
    public int getBoxLocation() {
        return this.boxLocation;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(50, 10));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
    }//GEN-LAST:event_formMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
