/*
 * VBorder.java
 *
 * Version 1.0
 * 
 * 16 May 2013
 */
package com.bixly.pastevid.screencap.components.capturebox;

import java.awt.Color;
import java.awt.GraphicsDevice;
import javax.swing.JWindow;

/**
 * Vertical border for the left and right sides of the CaptureBox.
 * @author June Millan
 */
public final class VBorder extends JWindow {
    // Location flags
    public static final int AT_LEFT = 0;
    public static final int AT_RIGHT = 1;
    private int boxLocation = AT_LEFT;
    
    public static final Color BORDER_COLOR = HBorder.BORDER_COLOR;
    public static final Color BORDER_FLASH_COLOR = HBorder.BORDER_FLASH_COLOR;
    

    /**
     * Creates new form VBorder.
     * @param location 
     */
    public VBorder(int location) {
        this.setBoxLocation(location);
        this.setFocusableWindowState(false);
        this.getContentPane().setBackground(BORDER_COLOR);
        this.setAlwaysOnTop(true);
        initComponents();
    }
    
    /**
     * Creates new form VBorder on the given GraphicsDevice.
     * @param location
     * @param device 
     */
    public VBorder(int location, GraphicsDevice device) {
        super(device.getDefaultConfiguration());
        this.setBoxLocation(location);
        this.setFocusableWindowState(false);
        this.getContentPane().setBackground(BORDER_COLOR);
        this.setAlwaysOnTop(true);
        initComponents();
    }

    /**
     * Sets VBorder location.
     * @param location 0 == AT_LEFT; 1 == AT_RIGHT;
     */
    public void setBoxLocation(int location) {
        this.boxLocation = (location > 1 || location < 0) ? AT_LEFT : location;
    }

    /**
     * Returns VBorder location (AT_LEFT|AT_RIGHT)
     * @return 
     */
    public int getBoxLocation() {
        return this.boxLocation;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(10, 50));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    protected void repositionResizeHandle() {
    }

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        repositionResizeHandle();
    }//GEN-LAST:event_formComponentResized

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
    }//GEN-LAST:event_formMouseEntered
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
