/*
 * PreviewPlayerSliderFloat.java
 * 
 * Version 1.0
 *
 * Created on Jun 7, 2012, 1:30:19 PM
 * 17 May 2013
 */
package com.bixly.pastevid.screencap.components.preview;

import java.awt.Cursor;

/**
 * Custom RecordFromHere panel display for Linux environments due to transparency issues.
 * @author cevaris
 */
public class RecordFromHereLinux extends javax.swing.JPanel implements IRecordFromHere {

    PreviewPlayer jpPreviewPlayer = null;
    
    /** 
     * Creates new form RecordFromHereLinux.
     */
    public RecordFromHereLinux(PreviewPlayer player) {
        initComponents();
        
        this.jpPreviewPlayer = player;
    }
    
    public void setLabelTextTimeCurrent(String text) {
        this.jlblTimeCurrent.setText(text);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblStaticRecordFrom = new javax.swing.JLabel();
        jlblTimeCurrent = new javax.swing.JLabel();
        jLblRecordFromHere = new javax.swing.JLabel();
        jLblBackground = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblStaticRecordFrom.setForeground(new java.awt.Color(255, 255, 255));
        jlblStaticRecordFrom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblStaticRecordFrom.setText("Record From");
        jlblStaticRecordFrom.setToolTipText("Current Time of Screen Capture");
        jlblStaticRecordFrom.setDoubleBuffered(true);
        add(jlblStaticRecordFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 110, 30));

        jlblTimeCurrent.setForeground(new java.awt.Color(255, 255, 255));
        jlblTimeCurrent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTimeCurrent.setText("TimeCurr");
        jlblTimeCurrent.setToolTipText("Current Time of Screen Capture");
        jlblTimeCurrent.setDoubleBuffered(true);
        add(jlblTimeCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 110, -1));

        jLblRecordFromHere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bixly/pastevid/resources/preview-player-slider-panel-record.png"))); // NOI18N
        jLblRecordFromHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLblRecordFromHereMouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLblRecordFromHereMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLblRecordFromHereMouseEntered(evt);
            }
        });
        add(jLblRecordFromHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, -1, -1));

        jLblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bixly/pastevid/resources/preview-player-slider-panel-linux.png"))); // NOI18N
        add(jLblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLblRecordFromHereMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblRecordFromHereMouseReleased
        this.jpPreviewPlayer.startRecordingFromHere();
    }//GEN-LAST:event_jLblRecordFromHereMouseReleased

    private void jLblRecordFromHereMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblRecordFromHereMouseEntered
        this.jLblRecordFromHere.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLblRecordFromHereMouseEntered

    private void jLblRecordFromHereMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblRecordFromHereMouseExited
        this.jLblRecordFromHere.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLblRecordFromHereMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblBackground;
    private javax.swing.JLabel jLblRecordFromHere;
    private javax.swing.JLabel jlblStaticRecordFrom;
    private javax.swing.JLabel jlblTimeCurrent;
    // End of variables declaration//GEN-END:variables

   
}
